FROM python:3.11-slim

WORKDIR /app

# Install required build tools
RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    curl \
    python3-dev \
    git \
    ninja-build \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Set env vars to force CMake build and disable GPU backends
ENV CMAKE_ARGS="-DLLAMA_CUBLAS=off -DLLAMA_METAL=off -DLLAMA_OPENCL=off"



COPY requirements.txt .
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8080

USER 1001

CMD ["python", "personal_story_app.py"]
